name: Discord Bot CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # 安裝依賴
    - name: Install dependencies
      run: npm ci
    
    # 運行測試
    - name: Run tests
      run: npm test
    
    # 設置 SSH 密鑰
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
    
    - name: Deploy to EC2
      run: |
        # 步驟 1: 準備部署文件
        mkdir deploy_temp
        rsync -av \
          --exclude='node_modules' \
          --exclude='.git' \
          --exclude='deploy_temp' \
          --exclude='deploy.tar.gz' \
          . deploy_temp/
        
        # 步驟 2: 打包文件
        cd deploy_temp
        tar -czf ../deploy.tar.gz .
        cd ..
        
        # 步驟 3: 傳輸到 EC2
        scp deploy.tar.gz ubuntu@ec2-3-81-80-170.compute-1.amazonaws.com:~/discord-bot/
        
        # 步驟 4: 在 EC2 上設置和部署
        ssh ubuntu@ec2-3-81-80-170.compute-1.amazonaws.com '
          # 確保目錄存在並進入
          mkdir -p ~/discord-bot
          cd ~/discord-bot
          
          # 備份 .env
          cp .env .env.backup 2>/dev/null || true
          
          # 解壓新文件
          tar -xzf deploy.tar.gz
          
          # 恢復 .env
          mv .env.backup .env 2>/dev/null || true
          
          # 安裝依賴
          npm install
          
          # 清理部署文件
          rm deploy.tar.gz
          
          # 啟動服務
          pm2 delete discord-bot 2>/dev/null || true
          pm2 start index.js --name "discord-bot"
          pm2 save
        '
        
        # 清理本地臨時文件
        rm -rf deploy_temp deploy.tar.gz
